jobs:
  mail_on_push:
    runs-on: ubuntu-latest
    with:
     server_address: smpt.gmail.com
     server_port: 465
     username: ${{secrets.MAIL_USERNAME}}
     password: ${{secrets.MAIL_PASSWORD}}
     subject: ${{github.repository}}
     body: ${{github.event.head_commit.message}}
     to: ${{github.event.pusher.name}}
   
    